// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DataController from "./data_controller"
application.register("data", DataController)

import EditmodalController from "./editmodal_controller"
application.register("editmodal", EditmodalController)

import TurbomodalController from "./turbomodal_controller"
application.register("turbomodal", TurbomodalController)

import ValidationController from "./validation_controller"
application.register("validation", ValidationController)
